env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
  - plugin:react/jsx-runtime
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: 'tsconfig.json'
plugins:
  - react
  - '@typescript-eslint'
  - prettier
  - react-hooks
  - import
rules:
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - warn
    - ignoreRestSiblings: true
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-empty-function': warn
  '@typescript-eslint/require-await': off
  '@typescript-eslint/unbound-method': off
  '@typescript-eslint/no-misused-promises': off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/prop-types: off
  '@typescript-eslint/restrict-template-expressions':
    - error
    - allowAny: false
  '@typescript-eslint/prefer-includes': error
  react/self-closing-comp:
    - error
    - component: true
      html: true
  no-debugger: warn
  import/namespace: off
  import/no-named-as-default: off
  import/default: off
  import/order:
    - warn
    - groups:
        - builtin
        - external
        - internal
      newlines-between: always
      alphabetize:
        order: asc
  react/no-unused-prop-types: warn
  no-shadow: off
  no-undef: off
  '@typescript-eslint/no-explicit-any': warn
  no-console:
    - warn
    - allow:
        - warn
        - error
  '@typescript-eslint/no-shadow': warn
  curly:
    - error
    - multi-line
  react/jsx-curly-brace-presence:
    - warn
    - never
  react/react-in-jsx-scope: off
settings:
  react:
    version: 'detect'
overrides:
  - files:
      - src/generated.tsx
      - src/introspection-result.ts
    rules:
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/explicit-module-boundary-types': off
      '@typescript-eslint/ban-types': off

ignorePatterns:
  - node_modules
  - build
  - tailwind.config.js
